version: '3.7'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
            -   mode: host
                protocol: tcp
                published: 8083
                target: 443
        volumes:
            - ${APP_DIR}:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available:/etc/nginx/sites-available
        expose:
            - "9000"

    php:
        build: php8.1
        expose:
            - 9000
        volumes:
            - ${APP_DIR}:/var/www
            - ./php8.1/php.ini:/usr/local/etc/php/php.ini
            - ./php8.1/conf.d:/usr/local/etc/php/conf.d
        depends_on:
            - mysql

    mysql:
        restart: always
        image: mysql:5.7.27
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - mysql-db:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
            - ./mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:rw
            - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:rw
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

volumes:
    mysql-db: